server:
  port: ${SERVER_PORT:8001}
  shutdown: graceful

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: identity
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:identity_db}?sslmode=require}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:30000}
      connection-timeout: ${DB_CONN_TIMEOUT_MS:30000}
      max-lifetime: ${DB_MAX_LIFETIME_MS:1800000}

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}
      timeout: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092

    consumer:
      group-id: ${KAFKA_GROUP:identity}
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.sprintforge.identity.*"
        spring.json.add.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        enable.idempotence: true

    listener:
      concurrency: ${KAFKA_CONCURRENCY:3}
      ack-mode: record

    topics:
      employee-created: ${KAFKA_TOPIC_EMPLOYEE_CREATED:employee.created}
      employee-retired: ${KAFKA_TOPIC_EMPLOYEE_RETIRED:employee.retired}
      employee-suspended: ${KAFKA_TOPIC_EMPLOYEE_SUSPENDED:employee.suspended}
      employee-reactivated: ${KAFKA_TOPIC_EMPLOYEE_REACTIVATED:employee.reactivated}
      email-verification-requested: ${TOPIC_EMAIL_VERIFICATION_REQUESTED:email.verification.requested}

    groups:
      default-group: ${spring.kafka.consumer.group-id}

security:
  jwt:
    secret: ${JWT_SECRET:secretkey}
    issuer: ${JWT_ISSUER:sprintforge-identity}
    access-ttl-minutes: ${JWT_ACCESS_TTL_MINUTES:15}

  refresh:
    ttl-days: ${REFRESH_TTL_DAYS:30}

  password:
    bcrypt-strength: ${BCRYPT_STRENGTH:10}

auth:
  set-initial-password:
    base-url: ${LINK_SET_INITIAL_PASSWORD_PATH:http://localhost:5763}
    endpoint: ${SET_INITIAL_PASSWORD_PATH:/identity/set-initial-password}

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:INFO}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:INFO}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${PUBLIC_HOST:localhost}
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:localhost}:${EUREKA_PORT:8761}/eureka/
